apiVersion: v1
kind: Service
metadata:
  labels:
    app: liferayf
  name: liferayf
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: liferayf
  type: NodePort

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: liferayf-config
  name: liferayf-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: liferayf
  name: liferayf
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: liferayf
  strategy:
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: liferayf
    spec:
      containers:
      - env: 
        - name: LIFERAY_JAVA_OPTS 
          value: -Xms2g -Xmx2g
        - name: LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE
          value: 0.0.0.0:11311
        - name: LIFERAY_WEB_PERIOD_SERVER_PERIOD_DISPLAY_PERIOD_NODE 
          value: "true"
        - name: LIFERAY_REDIRECT_PERIOD_URL_PERIOD_SECURITY_PERIOD_MODE 
          value: "domain"
        image: liferay/dxp:7.3.10-sp3
        resources:
          requests: 
            memory: "2048Mi"
            cpu: "2"
          limits: 
            memory: "4098Mi"
            cpu: "2"
        name: liferayf 
        ports: 
        - containerPort: 11311
        - containerPort: 8080
        readinessProbe: 
          httpGet:
            path: "/web/guest"
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 15
          failureThreshold: 3
          successThreshold: 3
        livenessProbe: 
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 20
          failureThreshold: 3
          successThreshold: 1
        volumeMounts: 
        - mountPath: /opt/liferay/data
          name: liferay-data
        - mountPath: /mnt/liferay
          name: liferayf-config
      restartPolicy: Always 
      volumes: 
      - name: liferay-data
        persistentVolumeClaim:
          claimName: liferay-data
      - name: liferayf-config
        persistentVolumeClaim:
          claimName: liferayf-config