apiVersion: v1
kind: Service
metadata:
  name: searchf
spec:
  ports:
  - protocol: TCP
    name: http
    port: 9200
    targetPort: 9200
  - protocol: TCP
    name: transport
    port: 9300
    targetPort: 9300
  selector:
    app: searchf
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: searchf-claim
  name: searchf-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: searchf
  name: searchf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searchf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: searchf
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms1g -Xmx1g
        - name: LCP_PROJECT_ENVIRONMENT
          value: local
        - name: LCP_SERVICE_ID
          value: searchf
        - name: LCP_SERVICE_SCALE
          value: "1"
        - name: cluster.name
          value: liferay_followers
        - name: cluster.routing.allocation.disk.threshold_enabled
          value: "false"
        - name: discovery.type
          value: single-node
        image: liferaycloud/elasticsearch:7.16.3-4.1.5
        resources:
          limits:
            memory: "2024Mi"
            cpu: "1"
        ports:
        - containerPort: 9300
        - containerPort: 9200
        name: searchf
        volumeMounts:
        - mountPath: /lcp-container
          name: searchf-claim
      restartPolicy: Always
      volumes:
      - name: searchf-claim
        persistentVolumeClaim:
          claimName: searchf-claim